<?php

namespace App\Modules\Icon\database\seeders;

use App\Modules\Icon\Models\Icon;
use App\Modules\Icon\Models\IconCategories;
use App\Modules\Icon\Models\IconFiles;
use App\Modules\Icon\Repositories\Eloquent\IconRepository;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;

/**
 * Seeds the second-generation icon set: a matched outline/solid pair for every
 * glyph.
 *
 * The first-generation library is outline only, so a design that wants a
 * filled weight has nothing to reach for. These glyphs are generated by
 * tools/generate-icons.cjs, which writes the artwork into
 * public/icons/v2 alongside a manifest.json describing every file. Reading
 * that manifest rather than a hand-written array is deliberate: the generator
 * is the single source of truth, so adding a glyph there needs no edit here.
 *
 * Runs independently of IconSeeder and does not touch its rows. Safe to run
 * repeatedly: every icon is matched on its title and updated in place.
 */
class IconV2Seeder extends Seeder
{
    private const MANIFEST = 'icons/v2/manifest.json';

    public function run(): void
    {
        $manifest = $this->readManifest();

        if ($manifest === []) {
            $this->command?->warn(
                'No v2 icon manifest at public/' . self::MANIFEST
                . ' - run "node tools/generate-icons.cjs" first.'
            );
            return;
        }

        $categoryIds = $this->categoryIds();
        $seeded = 0;
        $skipped = 0;

        foreach ($manifest as $entry) {
            $relative = $entry['file'] ?? null;
            $title = $entry['title'] ?? null;

            if (! $relative || ! $title) {
                $skipped++;
                continue;
            }

            $absolute = public_path($relative);
            if (! File::exists($absolute)) {
                // The manifest and the artwork are written together, so a
                // missing file means the two have drifted. Skip rather than
                // record a row pointing at nothing.
                $skipped++;
                continue;
            }

            $icon = Icon::updateOrCreate(
                ['title' => $title],
                [
                    'description' => $this->describe($entry),
                    'category_id' => $categoryIds[$entry['category'] ?? ''] ?? null,
                    'user_id' => null,
                    'is_premium' => false,
                    'is_active' => true,
                    'tags' => $entry['tags'] ?? [],
                    'style' => ($entry['style'] ?? 'outline') === 'solid' ? 'solid' : 'outline',
                    'file_svg' => $relative,
                    // Generated glyphs are vector only; there is no raster
                    // twin, and the gallery falls back to the SVG for preview.
                    'file_png' => $relative,
                ]
            );

            $this->seedFile($icon->id, basename($relative), $relative, File::size($absolute));
            $seeded++;
        }

        $this->refreshCategoryCounts();
        $this->flushIconCaches();

        $this->command?->info(
            "Seeded {$seeded} v2 icons" . ($skipped ? " ({$skipped} skipped)" : '') . '.'
        );
    }

    /** @return array<int,array<string,mixed>> */
    private function readManifest(): array
    {
        $path = public_path(self::MANIFEST);
        if (! File::exists($path)) {
            return [];
        }

        $decoded = json_decode(File::get($path), true);

        return is_array($decoded) ? $decoded : [];
    }

    private function describe(array $entry): string
    {
        $style = ($entry['style'] ?? 'outline') === 'solid' ? 'solid' : 'outline';

        return ($entry['title'] ?? 'Icon')
            . ' icon, ' . $style . ' weight, drawn on a 24x24 grid as scalable SVG.';
    }

    /**
     * Categories are already seeded by IconSeeder; this only resolves their
     * ids, creating one only if the generator introduced a new slug.
     *
     * @return array<string,int> slug => id
     */
    private function categoryIds(): array
    {
        $ids = IconCategories::query()->pluck('id', 'slug')->all();

        $missing = [];
        foreach ($this->readManifest() as $entry) {
            $slug = $entry['category'] ?? null;
            if ($slug && ! isset($ids[$slug]) && ! isset($missing[$slug])) {
                $missing[$slug] = true;
            }
        }

        foreach (array_keys($missing) as $slug) {
            $category = IconCategories::updateOrCreate(
                ['slug' => $slug],
                [
                    'name' => ucwords(str_replace('-', ' ', $slug)),
                    'description' => ucwords(str_replace('-', ' ', $slug)) . ' icons.',
                    'is_active' => true,
                ]
            );
            $ids[$slug] = $category->id;
        }

        return $ids;
    }

    private function seedFile(int $iconId, string $name, string $path, int $size): void
    {
        IconFiles::updateOrCreate(
            ['icon_id' => $iconId, 'file_type' => 'svg'],
            [
                'file_name' => $name,
                'file_path' => $path,
                'file_size' => $size,
                'dimensions' => '24x24',
            ]
        );
    }

    private function refreshCategoryCounts(): void
    {
        IconCategories::query()->each(function (IconCategories $category): void {
            $category->forceFill([
                'icon_count' => Icon::query()
                    ->where('category_id', $category->id)
                    ->where('is_active', true)
                    ->count(),
            ])->saveQuietly();
        });
    }

    private function flushIconCaches(): void
    {
        // The gallery caches resolved payloads per filter and per page, so the
        // keys cannot be enumerated - bumping the version retires them all.
        IconRepository::bumpCacheVersion();
    }
}
